export enum SERIALIZATION_GROUP {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
  VENDOR = 'VENDOR',
}

export const ADMIN_ONLY_GROUP = [SERIALIZATION_GROUP.ADMIN];
export const CUSTOMER_ONLY_GROUP = [SERIALIZATION_GROUP.CUSTOMER];
export const VENDOR_ONLY_GROUP = [SERIALIZATION_GROUP.VENDOR];
export const ALL_GROUP = [
  SERIALIZATION_GROUP.ADMIN,
  SERIALIZATION_GROUP.CUSTOMER,
  SERIALIZATION_GROUP.VENDOR,
];

/**
 * admin and customer group
 */
export const AC_GROUP = [
  SERIALIZATION_GROUP.ADMIN,
  SERIALIZATION_GROUP.CUSTOMER,
];

/**
 * admin and vendor group
 */
export const AV_GROUP = [SERIALIZATION_GROUP.ADMIN, SERIALIZATION_GROUP.VENDOR];

/**
 * customer and vendor group
 */
export const CV_GROUP = [
  SERIALIZATION_GROUP.CUSTOMER,
  SERIALIZATION_GROUP.VENDOR,
];
